- theme/locales/en.default.json
- theme/snippets/home-header.liquid
- theme/snippets/product-grid-item.liquid
- theme/styles/_config.scss
- theme/styles/_settings.scss
- theme/styles/_snippets.scss
- theme/styles/buttons.scss
- theme/styles/global.scss
- theme/styles/settings/_hover-state.scss
- theme/styles/settings/_radius.scss
- theme/styles/settings/_typography.scss
- theme/styles/snippets/product-grid-item.scss
- theme/templates/collection.liquid
- theme/templates/index.liquid
- Adds `Product Grid Item` and `Product Grid`
- In Shopify, the user can manually choose the order of the products in the `Featured Collection` (collection on the home page)
- Since they can choose the order, the first product will be the `Featured Product`. 
- In the Accentuate custom fields for `Collections`, there is a checkbox for `show_featured_product` layout. If true, the `first child` (first product) is given the classes to make it a larger, featured product.
- Every product can have an Accentuate custom field for `Featured Product Text` ("This week") 
Closes #39 
Closes #13 
https://jczdog9k04ldnnei-52674822324.shopifypreview.com
pw: nunu
- If you uncheck the box for "Show Featured Product" then you can see the 3 col grid without a `Featured Product`
- Go to the Collection > More …
> Add Product Grid Item and Product Grid

- theme/styles/buttons.scss
- theme/styles/settings/_typography.scss
- theme/styles/settings/_vars.scss
- theme/styles/templates.scss
- theme/styles/templates/page.scss
- theme/templates/page.liquid
- Adds Default Page Rich Text Styling (h1, h2, h3, table, etc)
- Does not add styling for images with captions.
Closes #29 
Closes #33 
Closes #35 
https://v1pit9s77i0c9lvh-52674822324.shopifypreview.com/pages/about
https://v1pit9s77i0c9lvh-52674822324.shopifypreview.com/pages/default-page-style-guide
pw: nunu
- Images with caption #28 #36
> Add Default Page Text Styling

- README.md
- theme/styles/global.scss
- theme/templates/index.liquid
- theme/templates/product.liquid
- Adds Related Products to Product Page (using accentuate custom metafields)
#17 
https://zzcua7nmw4nmdue0-52674822324.shopifypreview.com
pw: nunu
Click on Type Design 1 (first product on the homepage)
In Shopify:
> Add Related Products to Product Page

- theme/locales/en.default.json
- theme/snippets/news-feed-item.liquid
- theme/snippets/news-feed.liquid
- theme/styles/_snippets.scss
- theme/styles/global.scss
- theme/styles/settings/_typography.scss
- theme/styles/snippets/home-header.scss
- theme/styles/snippets/news-feed-item.scss
- theme/styles/snippets/news-feed.scss
- theme/templates/index.liquid
- Adds Homepage News Feed
- UPDATE: This is now a Markdown Text field in Accentuate. 
#9 
https://2qdzpaikvh3moqj3-52674822324.shopifypreview.com
pw: nunu
Pt 2: Add the News page. #31 
- Add News Feed Limit field, so they can choose how many rows to show. It is currently hardcoded to be 4 on the homepage.
> Add Homepage News Feed

- theme/snippets/news-feed-item.liquid
- theme/snippets/news-feed.liquid
- theme/styles/global.scss
- theme/styles/snippets/news-feed-item.scss
- theme/styles/snippets/news-feed.scss
- theme/styles/templates.scss
- theme/styles/templates/news.scss
- theme/templates/index.liquid
- theme/templates/page.news.liquid
- Adds News page template
- Small modifications to `news-feed.liquid` so that the news feed limit changes depending on the page. The home page feed should be limited to 4 with a "See More" button, while the news page feed should be unlimited. 
#32 
https://hayoijrzxmxvv0ly-52674822324.shopifypreview.com/pages/news
pw: nunu
> Add News Page

- theme/snippets/knowledge-area-header.liquid
- theme/snippets/knowledge-area-markdown.liquid
- theme/styles/_snippets.scss
- theme/styles/global.scss
- theme/styles/settings/_radius.scss
- theme/styles/snippets/knowledge-area-header.scss
- theme/styles/snippets/knowledge-area-markdown.scss
- theme/styles/templates.scss
- theme/styles/templates/knowledge-area.scss
- theme/templates/page.knowledge-areas.liquid
- Added a tiny bit of styling to the placeholder Nav so it's nicer to look at!
- Adds Knowledge Area page template
- Adds `Knowledge Area Header` and `Knowledge Area Markdown` snippets
- When the user creates a new page, they click on the `Knowledge Areas template`. Pages using the `Knowledge Areas template` have access to the Knowledge Area Accentuate custom fields. 
**What the Accentuate global values look like (Editors will need to create these in globals, and then reference them in a Page's Accentuate field):**
**The editors will reference these global values here, in the Page's Accentuate fields:**
#21 
Closes #23
https://b7porruvzd1f1rm4-52674822324.shopifypreview.com/pages/birding
pw: nunu
> Add Knowledge Area Header and Knowledge Area Markdown

- theme/snippets/knowledge-area-markdown.liquid
- theme/snippets/markdown.liquid
- theme/snippets/nav.liquid
- theme/snippets/product-grid-item.liquid
- theme/snippets/product-info-bar.liquid
- theme/styles/_snippets.scss
- theme/styles/global.scss
- theme/styles/snippets/footer.scss
- theme/styles/snippets/markdown.scss
- theme/styles/snippets/product-info-bar.scss
- theme/templates/product.liquid
- Adds Product Description Markdown styling 
- Adds Accentuate field: `product_description` (markdown) 
- Adjust `Footer` button media query
- Adds styling of the `ProductInfoBar`. Add to cart functionality will be in another PR. I'm not sure how add to cart works yet, and wanted to get some styling in there in the meantime. Note: Right now "Type Design" is a tag coming from Shopify. This will change in the future when we start to use Shopify Bookings. 
**NOTE: There were a lot of features cut for the MVP to be able to launch faster. The biggest features cut were Knowledge Areas, the Menu Filter for Offerings, and on Product Pages (what this PR covers) we are using markdown only for the product description. Product pages don't have a menu dropdown either.** @sepowitz @limsohee1002 
Closes …
> Add Product Description Markdown and Product Info Bar

- theme/locales/en.default.json
- theme/snippets/cart-item.liquid
- theme/styles/_reset.scss
- theme/styles/_snippets.scss
- theme/styles/buttons.scss
- theme/styles/snippets/cart-item.scss
- theme/styles/templates.scss
- theme/styles/templates/cart.scss
- theme/templates/cart.liquid
- theme/templates/product.liquid
- Adds styling of `DrawerCart`
- This is still viewable at `/cart`, the way Shopify builds it. In Pt. 2 I will implement the actual "drawer" functionality and use the Cart object instead of linking to `/cart`.
#66 
https://jm0pcqdocv8k913p-52674822324.shopifypreview.com
pw: nunu
Click on `Cart`
**Note: It takes the full width of the page but the styling should be the same when it is made the size of the Drawer Cart in pt 2. Will adjust styling if needed.**
Empty cart: 
- In Pt. 2 I will implement the actual "drawer" functionality and use the Cart object instead of linking to `/cart`.
> Drawer Cart styling Pt. 1

- theme/snippets/nav.liquid
- theme/styles/_config.scss
- theme/styles/global.scss
- theme/styles/settings/_transitions.scss
- theme/styles/settings/_vars.scss
- theme/styles/snippets/nav.scss
- Updates Nav styling
- Adds some transitions to the mobile menu
- **NOTE: Icons were cut.**
Behavior: 
- Hover over a main nav link and the link should have a black bg/white font with rounded borders
- An active link should have the same hover styling
https://e7ao9dyu8xniorpf-52674822324.shopifypreview.com
pw: nunu
Designs:
- May need to change transitions when XXIX sees/QAs the nav.
> Update Nav Styling

- theme/styles/snippets/product-images-slider.scss
Removes black flash seen when cycling through slide on the ProductImageSlider
https://zdnveagziu3y2u56-52674822324.shopifypreview.com
- View it on safari (compared to current master on index-space.org)
- View it on mobile browsers
> QA: Black flash on image slider

- theme/snippets/product-grid-item.liquid
Updates product grid item to accommodate two-line product titles
https://u5x8wf2h5yzf79xf-52674822324.shopifypreview.com
- Resize screen width on offerings collection to see two line product variants
> QA: Two Line Products

- theme/snippets/product-info-bar.liquid
- theme/styles/snippets/markdown.scss
- Use Dingbats Font when using `<strong>` styling in Markdown h1 - h6, p, ol, ul
- Also fixes QA issue: Price / product name misalignment
https://9iafk3303qx338cx-52674822324.shopifypreview.com
(Should see some random test words with dingbats)
> QA: Use Dingbats Font when using <strong> styling in Markdown

- theme/scripts/productImagesSlider.ts
- theme/styles/settings/_transitions.scss
- theme/styles/snippets/product-grid-item.scss
- theme/styles/snippets/product-images-slider.scss
- Update product grid animations and add drag to product images slider
QA tickets: 
I should be able to swipe PDP image galleries on Mobile
IMO: The upward animation when images fade in is "a bit much". Can we just do the opacity fade and lose the up-and-in?
https://jr2833b9kaw3v10h-52674822324.shopifypreview.com
> QA: Update Product Grid animations and make Product Images Slider images swipeable on mobile

- theme/snippets/news-feed.liquid
- Homepage news feed will only show news feed items with dates in the future, or equal to today's date.
- News page news feed shows all news feed items.
- Added an Accentuate field `news_feed_happens_at` (date field) so editors will need to add this date when they're creating news feed items.
QA ticket: Items in the "News Feed" should have a happens_at timestamp that means a past item will not show on the homepage, and only show in a special: "In the Past" section of /news
- By changing the Accentuate field `news_feed_happens_at` dates to past dates and future dates to see if they appear in the homepage news feed.
https://p6k47s04h4xyow0y-52674822324.shopifypreview.com
- TBD: Add design for an "in the past" section on the News page.
> QA: Hide past news items from Homepage news feed

- theme/styles/templates/product.scss
- In the Shopify Product Description editor, if you don't select Paragraph, h1, h2, etc, I think it defaults to span. We didn't have any styling for span so I've added it in this PR.
QA ticket: https://www.notion.so/garden3d/ba130e56c01f4d9284d8bbf6cf59ba0f?v=133f51dd370c40ad981fef24024fa8b6&p=4c7865dc18a5447aaeb92d0c6b9a76ae
https://btvc3c5d3qq49m3g-52674822324.shopifypreview.com
View /products/oase104-the-urban-household-of-metabolism
> QA: Add styling for <span> in Product Description

- theme/locales/en.default.json
- theme/snippets/product-date.liquid
- theme/snippets/product-images-slider.liquid
- theme/snippets/product-info.liquid
- theme/styles/snippets/product-grid-item.scss
- theme/styles/snippets/product-images-slider.scss
- theme/templates/product.liquid
- This PR makes the PDP date icon a "shop" level Accentuate custom field instead of a hardcoded image
Related docs in the Website Manual: https://docs.google.com/document/d/1XC4-oTJ3RPY8itahtwWSckqHQqCYO8rHDwoNCUedUlA/edit#heading=h.e7rtmgct5fu0
- Also makes a few styling adjustments so the hero slider has a [rounded border radius as you swipe](https://share.getcloudapp.com/bLuqgd0A). (Note: This non-urgent ticket came after the QA issues covered in #199, and I wanted to keep this one separate from #199 because that's our "launch ready" branch/theme)
https://3nm13lwf8cvc0ptj-52674822324.shopifypreview.com
You should see a sun icon next to a Bookings product's date.
> [DO NOT MERGE] QA: Make PDP date icon an Accentuate custom field

- theme/templates/product.liquid
Quick fix to add the date/time snippet to the mobile view of the PDP. 
These types of problems occur because the desktop and mobile info section of the PDP is split up between the main `product` template and the `product-info` snippet. Developers have to add the same things in both spots and it's easy to miss one.
In the future, it would make sense to try and change both desktop and mobile to use `product-info` so it does not repeat. Although, if we do end up switching all of Index to headless, this may not be worth the effort since the PDP won't change too much till then.
https://garden3d.notion.site/Course-date-and-time-doesn-t-appear-on-mobile-105c7e12f38f4cd99bef845bc6d8d715
Tested on Chrome dev tools and my iphone!
> add date-time snippet to mobile

- theme/snippets/product-instructor.liquid
- Add Resource Role field to Accentuate 
- If this field is blank, this defaults to "Instructor"
- Design request
https://kc6cm67rleh41aqg-52674822324.shopifypreview.com
- If you visit `products/caps-lock-a-book-talk-with-ruben-pater`, the role should say "Featured Speaker".
> Make Resource Role editable in Accentuate

- theme/snippets/meta.liquid
- Adds accentuate metafield for custom share card images on pages where `template contains 'page'`. Eg. on any Liquid templates named `page.page-name.liquid`.
- This does not effect non-top-level pages such as products, collections, blog posts, etc.
Enable share card images for the new Join page launching tomorrow.
Tested with the Join page
> Add accentuate metafield for custom share card images on page templates

- theme/scripts/patronsList.ts
Adds mock patron names to the patrons list to seed tje [page
Make the PALs program seem more active at launch
Tested in Firefox
> Add mock names to patron list, return if no name exists

- theme/scripts/patronsList.ts
temporarily reverse the order of data returned from the Patrons API endpoint.
Display the most recent patrons first until @hhff can do this on the API side in ~2 weeks.
tested in Firefox with current patron list
Revert this once it is handled by the API
> temporarily reverse patron list from API

- .tool-versions
- theme/scripts/accountResetRedirect.ts
- theme/scripts/index.ts
**Loom vid:** https://www.loom.com/share/cb08aa52603e4dcbaaacb7ba692d5f21
This PR adds a script that adds a redirect from the `/account/reset` route of the Shopify theme to the `https://members.index-space.org/reset-password` page. 
This is from an issue within the `index-space` repo: https://github.com/sanctuarycomputer/index-space/issues/175
Along with this added code, Index's customer accounts setting was changed to "accounts are optional" from "accounts are disabled". Note that this change changes the checkout page to add a little note to sign in if you can have an account which is quite minor:
However, if someone does end up clicking that, it takes them to `/account/login` route of the Shopify theme which is a blank page.
https://github.com/sanctuarycomputer/index-space/issues/175 …
> add reset password redirect script

- theme/templates/collection.liquid
This PR adds liquid pagination logic to render more than 50 products on a collection page. The limit is set to 1000 right now to ensure we won't run into a limit like this in the future.
Elie asked for this on Twist: https://twist.com/a/133876/ch/376069/t/2382693/c/74007166
Tested through this preview on the books collection which currently has more than 50 products: https://l8ez4qdi31ruyobl-52674822324.shopifypreview.com
> allow collections to show more than 50 products

- theme/snippets/add-to-cart-container.liquid
- theme/snippets/product-grid-item.liquid
- theme/snippets/product-registration-state.liquid
This PR adds date fields for products in Accentuate named `starts_at` and `ends_at` that signify the start date and time plus end date and time for events, courses, and workshops.
The flow and logic is the same as it used to be with bookings dates so I only needed to add code to retrieve the dates from accentuate metafields. The same `liquid` variables used to store the bookings dates are overrided with the dates from accentuate if they exist. This means Accentuate will have the 'final say', but bookings data will still be used for old events.
The date + time field in Accentuate uses UTC time so I added a description letting editors to know to adjust their times to UTC when entering them:
Registration status and the add to cart button state for events/courses were controlled through …
> setup fields in accentuate and add them to logic

- theme/snippets/product-registration-state.liquid
There was a typo in the last PR that I found before publishing the theme. Instead of `ends_at`  in the if check, I had written `end_at`.
theme with this fix applied: https://k32rl6c2xhzvaglc-52674822324.shopifypreview.com
> fix typo by changing end_at to ends_at

- theme/snippets/product-description.liquid
Changes the checking logic that determines which product description design to render.
**Before:** Show accentuate product description if it is a bookings product of the course type
**Now:** The above OR if the product is either a `event`, `course`, or `workshop` and the description `title` and `markdown` fields from accentuate are not empty.
Sam asked for this on Twist because we are not using Bookings on Index anymore.
Tested through a non bookings event product by adding and removing the Accentuate description to see what renders. Also ensured past bookings products still show the accentuate description and non event/course/workshop products still show the regular shopify description.
Preview link: https://movqrsx6mn4kh896-52674822324.shopifypreview.com
> adjust description to use accentuate description if fields are not empty and product type matches

- theme/snippets/nav.liquid
- theme/styles/_snippets.scss
- theme/styles/snippets/collection-subnav.scss
- theme/templates/collection.liquid
Closes INDEX-100 by adding a sub-nav which lists links to product collections.
- This menu is configurable within the Shopify Theme navigation settings [here](https://nunu-school.myshopify.com/admin/menus/194455503028).
- When we ship this, we'll probably replace collection links in the main nav with a single `Shop` menu.
- https://www.notion.so/garden3d/Shopify-Collections-build-f3cb0c7df99c4514b745b1176bfb9610
- https://www.notion.so/garden3d/Shopify-Collections-Design-Review-56f363fa917849148dca24085edf8625
- Tested on desktop and mobile, Firefox and Safari. This code is modified from the PDP details subnav.
- Main nav item selected, which has child links
- Main nav item selected, and items wrap to new rows
- Child collection nav item active
- Main nav item active, with no child links
> Add collections subnav to collection template

- theme/styles/settings/_vars.scss
- theme/templates/collection.liquid
Fixes an issue where the new collection subnav introduced in #232 is z-indexed above the mobile nav.
Adjusts `$nav-height` to be the right value after #213 changed the intrinsic height.
> Fix z-index of subnav and nav-height on mobile
