sanctuarycomputer/nunu

theme/templates/product.liquid

- Adds Product Title and Vendor to the Product Page
#40 
https://paacy0nxt2v8jn2h-52674822324.shopifypreview.com
pw: nunu
Click on any product on the homepage

Add Product Heading

---

theme/snippets/product-info-bar.liquid
theme/styles/settings/_typography.scss
theme/styles/settings/_vars.scss
theme/styles/snippets/footer.scss
theme/styles/snippets/home-header.scss
theme/styles/snippets/knowledge-area-markdown.scss
theme/styles/snippets/markdown.scss
theme/styles/snippets/news-feed-item.scss
theme/styles/templates/page.scss
theme/templates/product.liquid

Updates type styles using new type chart in the designs. 
#65 
https://91x66tj81cgl4h7m-52674822324.shopifypreview.com
pw: nunu

Sitewide Type Pass

---

theme/snippets/news-feed-item.liquid
theme/snippets/news-feed.liquid
theme/styles/snippets/news-feed-item.scss
theme/styles/snippets/news-feed.scss

- Styling adjustments according to the design changes
- The entire row should be clickable
- Rows should not scroll horizontally, the text should wrap
https://rpeo9uv08za3fq8h-52674822324.shopifypreview.com
pw: nunu
View at homepage and by clicking on the News link in the nav
Design:

News Feed styling adjustments

---

README.md
theme/layout/theme.liquid
theme/locales/en.default.json
theme/snippets/cart.liquid
theme/snippets/cookie-consent.liquid
theme/snippets/home-header.liquid
theme/snippets/product-grid-item.liquid
theme/styles/_config.scss
theme/templates/collection.liquid
theme/templates/product.liquid

- Sitewide little changes for accessibility (mostly adding missing alt tags, h1, etc.)
#86 
Axe
Lighthouse 
- Will do a second pass during QA

Accessibility Pass

---

theme/styles/snippets/markdown.scss
theme/styles/templates/product.scss
theme/templates/product.liquid

- Removed use of Markdown snippet for Product Description because of the video request. I showed XXIX the process with Accentuate, and they were prefer having less control (and markdown) for the Product Description, and just using the Shopify rich text editor.
- Adds styling to `Product` snippet for the product description text
https://q87hcedr974lzwvp-52674822324.shopifypreview.com
pw: nunu
View product Type Design I to see the Video embed

QA: Product Description 

---

theme/snippets/cookie-consent.liquid
theme/snippets/footer.liquid
theme/snippets/home-header.liquid
theme/snippets/news-feed-item.liquid
theme/styles/buttons.scss
theme/styles/global.scss
theme/styles/settings/_vars.scss
theme/styles/snippets/footer.scss
theme/styles/snippets/home-header.scss
theme/styles/snippets/markdown.scss
theme/styles/snippets/news-feed-item.scss
theme/styles/templates/product.scss
theme/templates/page.liquid
theme/templates/page.news.liquid

Addresses these Notion QA issues:
- Site border (adds 0.125rem border to the site)
- Header Spacing
- Typography mobile
- Typography
See description
https://ocibz3pvozj9ao53-52674822324.shopifypreview.com
pw:nunu

QA: Typography, Header Spacing, Site Border

---

theme/snippets/news-feed-item.liquid
theme/styles/global.scss
theme/styles/settings/_vars.scss
theme/styles/snippets/news-feed-item.scss
theme/styles/snippets/news-feed.scss

QA: News Feed

---

theme/styles/_reset.scss

Couldn't explicitly repro this issue, but added (what will hopefully be) a fix.

QA: Overflow mobile

---

theme/snippets/news-feed-item.liquid
theme/styles/_config.scss
theme/styles/snippets/news-feed-item.scss

[Address additional news feed item QA](https://www.notion.so/garden3d/News-Cell-Spacing-2d043bc600094d4e849fab6f3dddf1dd)
https://07h55rkbj13j9oow-52674822324.shopifypreview.com

QA: News Feed Item

---

package.json
theme/locales/en.default.json
theme/scripts/emailSubscribe.ts
theme/scripts/index.ts
theme/snippets/email-subscribe.liquid
theme/snippets/footer.liquid
theme/snippets/home-header.liquid
theme/styles/buttons.scss
theme/styles/snippets/email-subscribe.scss
theme/styles/snippets/footer.scss
theme/styles/snippets/markdown.scss
yarn.lock

- Changes the `button--style-primary` to `button--style-rounder-border-sm` and `button--style-rounded-border-xs`
Address these QA issues:
https://5fyk5u3u180bal97-52674822324.shopifypreview.com
pw: nunu

QA: Email signup

---

theme/locales/en.default.json
theme/snippets/product-grid-item.liquid
theme/snippets/product-info-bar.liquid
theme/snippets/product-vendor.liquid
theme/styles/_snippets.scss
theme/styles/snippets/product-grid-item.scss
theme/styles/snippets/product-vendor.scss
theme/templates/product.liquid

- Renders correct product type in grid item
- Renders avatar on grid item (when appropriate)
- Renders avatar on pdp (when appropriate)
https://646okc8c4vo5lnn7-52674822324.shopifypreview.com
- Go to offerings
- At the bottom of the page, you will see two test events with avatars showing

Adds avatar logic

---

theme/locales/en.default.json
theme/snippets/collection-links.liquid
theme/snippets/news-feed.liquid
theme/snippets/product-grid-item.liquid
theme/snippets/product-images-slider.liquid
theme/snippets/product-info-bar.liquid
theme/styles/_snippets.scss
theme/styles/buttons.scss
theme/styles/global.scss
theme/styles/settings/_typography.scss
theme/styles/settings/_vars.scss
theme/styles/snippets/collection-links.scss
theme/styles/snippets/news-feed.scss
theme/styles/snippets/product-grid-item.scss
theme/styles/snippets/product-info-bar.scss
theme/styles/snippets/product-vendor.scss
theme/styles/templates/product.scss
theme/templates/index.liquid
theme/templates/product.liquid

QA Items:
- Text Highlighting should invert colors (black highlight, white text)
- Product Description feels a little too wide to be naturally readable
- The typography relationship on the Collection card bugs my eyeballs out a bit
- Homepage Product Area
- Product Type on the PDP isn't vertically centered
- PDP Product title
See description
https://9hyczm9245opjoy1-52674822324.shopifypreview.com
pw: nunu

QA: PDP, Product Grid Item, Collection Links Module

---

theme/styles/snippets/markdown.scss
theme/templates/page.liquid

Following these requests: https://www.notion.so/garden3d/ba130e56c01f4d9284d8bbf6cf59ba0f?v=133f51dd370c40ad981fef24024fa8b6&p=abb905629a20438c9ba5c194cbb9f84a
https://v9mz5y8ea33sdzdz-52674822324.shopifypreview.com

QA: Update markdown styling

---

theme/snippets/image-caption-module.liquid
theme/styles/_snippets.scss
theme/styles/snippets/image-caption-module.scss

- Adds two up image module with Accentuate
View at About page: https://djjtu9si5kdb79k5-52674822324.shopifypreview.com
(top images)

Add Two Up Image Module

---

theme/snippets/email-subscribe.liquid
theme/snippets/nav.liquid
theme/snippets/product-grid-item.liquid
theme/snippets/product-info-bar.liquid
theme/styles/_config.scss
theme/styles/buttons.scss
theme/styles/snippets/email-subscribe.scss
theme/styles/snippets/markdown.scss
theme/styles/snippets/product-grid-item.scss
theme/styles/snippets/product-info-bar.scss
theme/styles/templates/product.scss

Mostly padding and font size changes!
- Email capture hover state
- Cart and nav padding 
- Add an <a> style to PDP links
See description
https://q7z9y8bm15dc1fsh-52674822324.shopifypreview.com

QA: Email signup hover state, ProductInfoBar padding, Product Description link styling

---

theme/scripts/index.ts
theme/scripts/pageTransition.ts
theme/snippets/product-images-slider.liquid
theme/styles/global.scss
theme/templates/product.liquid

- Higher res images on product.liquid and product image slider
- Add subtle page transitions
https://xifpev6fbp945do6-52674822324.shopifypreview.com

QA: Page Transitions

---

theme/snippets/collection-links.liquid
theme/snippets/news-feed.liquid
theme/styles/buttons.scss
theme/styles/settings/_typography.scss
theme/styles/snippets/footer.scss
theme/styles/snippets/markdown.scss
theme/templates/index.liquid

- Added some mobile font sizes for elements on the home page
- Made button padding/line height crop more consistent
https://1wg38neyjgeka8b9-52674822324.shopifypreview.com

QA: Home mobile typography and button consistency

---

theme/snippets/cart-empty.liquid
theme/styles/_snippets.scss
theme/styles/snippets/cart-empty.scss
theme/styles/snippets/cart.scss

Fix empty cart state mobile
https://3uthqj1yo1f60ny8-52674822324.shopifypreview.com

QA: Fix Empty Cart State Mobile

---

theme/locales/en.default.json
theme/snippets/email-subscribe.liquid
theme/snippets/meta.liquid
theme/snippets/nav.liquid
theme/styles/buttons.scss
theme/styles/global.scss
theme/styles/settings/_typography.scss
theme/styles/settings/_vars.scss
theme/styles/snippets/cart.scss
theme/styles/snippets/email-subscribe.scss
theme/styles/snippets/footer.scss
theme/styles/snippets/markdown.scss
theme/styles/snippets/nav.scss
theme/styles/snippets/product-info-bar.scss

- Update SEO description and title
- Nav Breakpoint too wide
- Default Page inline Headers
- Product rollover border-radius
- Footer signup shrunk?
- Logo up 2 px
- Page titles not showing up
- Placeholder in Email Signup is not Vertically Centered 
- Homepage footer padding
https://bbtxxss7m0izi5hm-52674822324.shopifypreview.com

QA: Misc padding, Update SEO defaults

---

package.json
theme/scripts/fadeIn.ts
theme/scripts/index.ts
theme/scripts/utils/isInViewport.ts
theme/scripts/utils/throttle.ts
theme/snippets/product-grid-item.liquid
theme/styles/settings/_transitions.scss
theme/styles/snippets/product-grid-item.scss
yarn.lock

QA issue:
N2H: Can we have Images in the Product Collection pages fade in when they come into view?
https://lfbim84bpvo3dm7z-52674822324.shopifypreview.com

Add Product Grid Image Fade In 

---

theme/scripts/fadeIn.ts
theme/snippets/product-grid-item.liquid

FIx: Fade in Throttle

---

theme/locales/en.default.json
theme/snippets/collection-links.liquid
theme/snippets/meta.liquid
theme/snippets/product-info-bar.liquid
theme/styles/_config.scss
theme/styles/buttons.scss
theme/styles/global.scss
theme/styles/settings/_typography.scss
theme/styles/settings/_vars.scss
theme/styles/snippets/cart.scss
theme/styles/snippets/nav.scss
theme/styles/snippets/product-info-bar.scss

- Add page titles (`<title>` in meta snippet)
- Remove price next to Add to Cart button in ProductInfoBar
- Misc little padding changes
https://h8reteui1u7pyw3b-52674822324.shopifypreview.com

QA: Misc fixes

---

theme/styles/snippets/cart.scss

Noticed some subtle misaligmnet in the cart header and adjusted the cart icon breakpoint to match the overall nav
https://ny146lgdjvcrvx3u-52674822324.shopifypreview.com

QA: Cart Header tweak

---

README.md
theme/snippets/meta.liquid
theme/snippets/product-grid-item.liquid
theme/styles/global.scss
theme/templates/collection.liquid

- Minor padding fixes
- Changing hyphen to em dash
- Allow for featured product layout setting to be used on all Collections and not just the Homepage collection 
https://crugykd3mxeiqkq5-52674822324.shopifypreview.com

QA: Logo padding, SEO title change

---

theme/locales/en.default.json
theme/snippets/footer.liquid

Adds contact us

---

theme/snippets/cart-empty.liquid
theme/snippets/news-feed-item.liquid
theme/snippets/news-feed.liquid

Image optimization

---

theme/scripts/cart.ts

Fix : Add to cart bug

---

theme/scripts/cart.ts
theme/snippets/cart-inner.liquid
theme/snippets/cart-item.liquid
theme/styles/settings/_vars.scss
theme/styles/snippets/cart-item.scss
theme/styles/snippets/cart.scss

- Adds Quantity Spinner to Cart
Allow users to buy more!
Designs:

Add Quantity Spinner to Cart

---

README.md
theme/layout/theme.liquid
theme/scripts/index.ts
theme/scripts/magicMouse.ts
theme/styles/global.scss

Please see below:
https://www.loom.com/share/d026d54faf604b379c091dfcc9bfdd8c

Adds Magic Mouse feature

---

theme/layout/theme.liquid
theme/snippets/stream.liquid
theme/styles/_snippets.scss
theme/styles/snippets/stream.scss

Demo below:
https://www.loom.com/share/df0046aa44844658a6e3f475550a0af3

Ability to enable a Twitch Stream embed on the site

---

theme/layout/theme.liquid
theme/scripts/magicMouse.ts

Fix Magic mouse

---

.github/workflows/deployer.yml
theme/templates/index.liquid

Branch Deploys

---

.github/workflows/deployer.yml

Run action on merge

---

.github/workflows/deployer.yml

Pinned Branches

---

.github/workflows/deployer.yml

Update to v10

---

theme/snippets/product-grid-item.liquid
theme/styles/global.scss
theme/styles/snippets/product-grid-item.scss

- Minor styling adjustments to the size of Product Grid Images
- QA request
Reviewed by Jake and Elie
https://cmg3tua210eeaabn-52674822324.shopifypreview.com

QA: Adjust Product Grid Image Sizing

---

theme/scripts/patronsList.ts

Fix typo in patron list for Elie
Spell her name right
My EYES

Fix elie's name

---

theme/locales/en.default.json
theme/snippets/footer.liquid

Adds Discord link to the footer
Elie asked
Visually in firefox

Add discord link to footer.
